
sudo: required
language: java

jdk:
  - oraclejdk7
  - openjdk7  
  


script:
  - mvn clean cobertura:cobertura -Dtest=SolrClientTest#testUpdate -DfailIfNoTests=false

before_deploy:
- tar -zcvf coverage-result.tar.gz /home/travis/build/leusonmario/YCSB/target/site/cobertura

deploy:
  provider: releases
  api_key:
    secure: "eAU8kgn3IUX88AddSt/1jWVlzzY7joy89Xuo37SqTvVaWYPMjmrNjDPsST15ndMnL66/D8zljejMFOh51AXJby3qIa0ZGMDOyUmFuGGZjUT+eyMNP6nrYJ7irS/sTJOUmzJdu5Ys15TzfrjQ7hJjSDnafHSPGnEK5XeCsEDUj2DeHWtTKamfldHYVh8h1zFn0kRq6HggMBN3Lq4d+sU2gHnu9Edi1DVD086SIJp4jJka8GqRrS1AiBUrk7Sf6z8Bq7aUGJ7YYHsXlV7ajGexr79jhYCgd2ktwMrKZ+EfGfKvOj0TOXL0H2ZByAp0P9RaE0oWYGxMBS28Oq9tpywelX/f1eUYVtRjFy7sWp6EtvF0Kb6iTMDS+mWB3JPZKN9Wi9dDoyHH8qPXmlj5aNOjvGrj7FLgKXJBT6J9lMwlwzIsHZOrF4OZIxY/liH0JN5B3+hwX6mK1v69mdtFECukKv2bvoGejRogeRMME+aHsj370WsqZT94lIVEkCrwmhnb0rK4+vw7OjPrIMZTfxLFvz9q9PRbsfSCa3FDh8yPi17O5LTm08c1didrAPCkSM8mFo7nVIVSLj/r7+mWE83J6zs4YkGhT40oVDFiSruR8HODRQYp/32uZF1KiyI/sdexMEcovdnWoPHfES/HOne95l3uI+M2CY7lJCcumnshaJs="


  file: coverage-result.tar.gz
  file_glob: true
  overwrite: true
  skip_cleanup: true
  on:
    tags: true
